### ISSUE TITLE
This Project Needs A Name

### ISSUE THREAD

**Issue by stormecharette** [maine-cyber/mcsc-unisim#46]
This project has many code names: 

+ *UniSim* (which is already a simulation software suite's name)  
+ *Mocha* (because it's short and simple to type in debug code)  
+ *GUP* (stands for "great unnamed project")   
+ *___ENGINE_NAME* (a purposely obnoxious temporary name)
+ *BetaDome* (I don't know)  

This issue serves as a looming reminder to officially name this project.

**Comment by ksabochick** [comment]
We may have a name! After discussion with Ed, since he wants to update the MCSC website to show us off as his prized pupils, we have come up with....

M.E.T.I
Metropolitan Event Training Interface!
MCSC-METI!

It's not copyrighted or used by any known program (other than the Ministry of Economy, Trade, and Industry in Japan).

**Comment by stormecharette** [comment]
The Ministry of Economy, Trade, and Industry is going to be livid.
