### ISSUE TITLE
Debug: FileSystem Testing

### ISSUE THREAD

**Issue by ksabochick** [maine-cyber/mcsc-unisim#52]
## **Current Debugging Results**

NOTE: Any recommendations or bugs could be a mistake on my part. See code and results to confirm any issues before proceeding.

**Tested the following with success:**
The following tests were completed successfully and returned the expected results.
1. Creating a new file with File(file_path, file_name)
2. Returning the file path, file name, and file extension
3. Returning the full path of the file
4. Setting a new file name and returning new name and new full path

**Tested the following with possible bugs:**
The following tests were completed unsuccessfully or returned unexpected results.
1. Setting a new extension to the file
     _Explanation of issue:_ Setting a new extension, such as going from "filename.file" to ".newext", sets the extension of the file but does not affect the name or the file path. This means that when getName() or getFullPath() is called, the old extension ".file" is returned, but when getExtension() is called, ".newext" is returned. This could create possible issues or confusion when calling just the extension, as the new extension is not actually applied to the file.

**Portion of testing code (affected code bolded):**
  sk::String my_file_name = "filename.file";
  sk::FilePath file_path = sk::FilePath("my/file/path");
  sk::File file = sk::File(file_path, my_file_name);

  // Testing accessors to file elements
  sk::String fileNameOne = file.getName();
  sk::String fileExtensionOne = file.getExtension();
  sk::String fileFullPathOne = file.getFullPath();

  // Testing mutators and new accessors to file elements
  **file.setName("newfilename.new");
  file.setExtension(".newext");
  sk::String newFileName = file.getName();
  sk::String newExtension = file.getExtension();
  sk::String newFileFullPathOne = file.getFullPath();**

Results
 File created 
                             :: File name one: filename.file
                             :: File extension one: .file
                             :: Full path file one: my/file/path/filename.file
                             **:: New file name: newfilename.new
                             :: New file extension: .newext
                             :: New full path one: my/file/path/newfilename.new**
                             :: Executable: /home/ksabochick/Desktop/Hello/

More will be added as more testing is completed.

**Comment by ksabochick** [comment]
## **fileExists() Possibilities**

For changing the code of fileExists(), I found one recommendation that uses part of the C++ system library:

#include <sys/stat.h>
/**
 * Check if a file exists
 * @return true if and only if the file exists, false else
 */
bool fileExists(const char* file) {
    struct stat buf;
    return (stat(file, &buf) == 0);
}

It uses the stat() method to check the existence of the file.

Another possibility I've seen has been checking the _accessibility_ of the file:
bool is_file_exist(const char *fileName)
{
   std::ifstream infile(fileName);
   return infile.good();
}

This takes in the file name and checks for access on the system. (May be different than what's required of our code but I thought I'd include it)

**Comment by stormecharette** [comment]
@ksabochick Thank you for the information. I will take a look at these issues when I implement version 2 of the Filesystem Module.

**Comment by stormecharette** [comment]
# Filesystem Fixes & Update  

@ksabochick, I have pushed a new update #56 to the `development` branch. The update contains fixes to the bugs you reported as well as the new socket API. The new version of the Filesystem Module in #56 **is not backwards compatible with previous versions**. It is not guaranteed that any code written with the previous Filesystem code will work (that includes the Mocha engine, which I now need to fix).  

***

## File Extension Bug  

You had reported a bug where the file name of an `sk::File` did not update when the extension was set. I fixed this bug by removing extension data from `sk::File` entirely. Modern file extensions do not exist outside of GUIs. However, if you think a utility function like `sk::getFileExtension()` might be useful for some applications, we can add it to Filesystem Utilities.  

***

## `sk::FileExists()` Bug  

After some testing I found that the `sk::FileExists()` function in the Filesystem Utilities was not broken, it wasn't working correctly because of the format of the input file. I have rewritten `sk::FileExists()` so that it attempts to fix the input file path under certain circumstances. I get much better results now, but this function still needs to be tested vigorously.  

***

## Additional Changes to Filesystem  

Along with fixing these bugs I also enhanced Filesystem quite a bit. Here are some changes to look after and test:  

   * `sk::FilePath` is now mostly implemented for all operating systems, except for one function that is platform-dependent.  

   * `sk::FilePath` is now much smarter about fixing its trailing path delimiter. If a `FilePath` is constructed without a trailing delimiter, then it will scan its string for an existing delimiter and if it finds one, it will append it as the trailing delimiter. Otherwise it just appends the current OS's delimiter.  

   * The former `sk::isAbsolutePath(const sk::FilePath&)` function is now a member function in `sk::FilePath`. So if you have a `FilePath fp` you can call `fp.isAbsolute()` to test if it is an absolute path. This function works on any Linux/Unix or Windows path regardless of what operating system you're running on. This way you can manage multiple OS path types in any application.  

   * I added some more operator overloads to `sk::FilePath`.  

   * `sk::File`'s implementation is now completely cross-platform.  
 
   * `sk::File` no longer supports extension data. You can have as many `.` characters in a file name as you want, it doesn't treat it differently.  

   * `sk::File` is now much smarter about parsing  a path out of its name. If a `File` is ever constructed or modified with a file path buried in its file name, it will intelligently move it to its path field.  

   * I added comments to obscure code in `FilesystemUtilities`.  

   * I added two functions to `FilesystemUtilities`:  
      * `char getPathDelimiter()` - returns the current OS's path delimiter character.  
      * `bool directoryExists(const sk::FilePath&)` - determines if a given directory exists.   

***  

There are all sorts of spelling errors and possibly bugs in this new code. I also want to add a few more features at another time. Let me know if you find any more bugs or have other suggestions.
